namespace: project-a

commonLabels:
  owner: team1

resources:
  - ../base-template
  - developer-conditional-edit.yaml

patches:
  - target:
      kind: RoleBinding
      name: developer-access
    patch: |-
      - op: replace
        path: /subjects/0/name
        value: team1-developers@example.com
  - target:
      kind: Namespace
      name: default-name
    patch: |-
      - op: replace
        path: /metadata/name
        value: project-a