apiVersion: templates.gatekeeper.sh/v1
kind: ConstraintTemplate
metadata:
  name: storagebucketuniform
  annotations:
    description: >-
      Ensures that Google Cloud Storage Buckets have the uniform access field set to true
spec:
  crd:
    spec:
      names:
        kind: StorageBucketUniform
      validation:
        openAPIV3Schema:
          type: object
          description: >-
            Ensures that Google Cloud Storage Buckets have the uniform access field set to true
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package storagebucketuniform

        violation[{"msg": msg, "details": {}}] {
            not input.review.object.spec.uniformBucketLevelAccess
            msg := sprintf("Storage bucket %s must have uniform bucket-level access configured", [input.review.object.metadata.name])
        }
